# Configurações Gerais
ANO_AGENDA="0000"
LOCAL_EVENTO = "A definir"

# Configurações do XLSX
PASTA_IN_XLSX = "INFORME_O_NOME_DA_PASTA"
NOME_ARQUIVO_XLSX = "INFORME_O_NOME_DO_ARQUIVO.xlsx"

# Informações do novo arquivo xlsx, contendo as linhas que não foram importadas para o CSV
PASTA_XLSX_NAO_PROCESSADOS = "INFORME_O_NOME_DA_PASTA"
ARQUIVO_XLSX_NAO_PROCESSADOS = "INFORME_O_NOME_DO_ARQUIVO.xlsx"

# Configurações do CSV
PASTA_OUT_CSV = "INFORME_O_NOME_DA_PASTA"
NOME_ARQUIVO_CSV = "INFORME_O_NOME_DO_ARQUIVO.csv"